apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: udemy-ghanbari-ca-tls
spec:
  secretName: udemy-ghanbari-ca
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: udemy.ghanbari.ca
  dnsNames:
    - udemy.ghanbari.ca
    - www.udemy.ghanbari.ca